services:
  postgres:
    image: postgres:latest
    container_name: postgres_etnair
    env_file:
      - .env
    volumes:
      - etnair_db_data:/var/lib/postgresql/datay
      - ./.env:/.env
    networks:
      - etnair_network
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: etnair-api
    env_file:
      - .env
      - ./api/.env
    ports:
      - "${API_PORT}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - etnair_network


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_etnair
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - etnair_network

networks:
  etnair_network:
    driver: bridge

volumes:
  etnair_db_data:
    driver: local
