# Stage 1: Build the frontend
FROM node:20-alpine AS client-builder

WORKDIR /app

COPY package*.json .
COPY .npmrc .npmrc
RUN npm install

RUN rm .npmrc

COPY . ./

RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine


COPY ./configs/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=client-builder     app/dist/ /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]


