services:
  postgres:
    image: postgres:latest
    container_name: postgres_etnair
    environment:
      POSTGRES_USER: etnair_user
      POSTGRES_PASSWORD: etnair_pass
      POSTGRES_DB: etnair_db
    volumes:
      - etnair_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etnair_network

  api:
    build:
      context: ./api
    container_name: api_etnair
    environment:
      DB_HOST: postgres
      DB_USER: etnair_user
      DB_PASSWORD: etnair_pass
      DB_NAME: etnair_db
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - etnair_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_etnair
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@etnair.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8080:80"
    networks:
      - etnair_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
      - "9443:9443"
    networks:
      - etnair_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - etnair_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    ports:
      - "3001:3000"
    networks:
      - etnair_network

networks:
  etnair_network:
    driver: bridge

volumes:
  etnair_db_data:
    driver: local
  portainer_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local